Upgrade to scriptworker 41.0.0 and latest iscript version
mozilla-platform-ops/ronin_puppet pull request #350
Opened 2021-09-02 17:45 UTC by bhearsum

2021-09-02 19:21 UTC, escapewindow requested changes
idna has a major version bump, but the major blocker is tc should be >=40.

2021-09-03 13:47 UTC, bhearsum commented
> idna has a major version bump, but the major blocker is tc should be >=40.

Fixed the taskcluster issue. The idna major version bump is just for dropping python 2 support, no API changes AFAICT

2021-09-03 15:48 UTC, escapewindow submitted a review, later dismissed
Thanks!
Given yesterday, we may want to a) quarantine a prod mac, b) ssh in, c) disable the periodic puppet launch daemon, d) manually puppetize against master (I tend to edit /usr/local/bin/run-puppet.sh), e) possibly manually run script with `mac_notarize` behavior to get one round trip sign+notarize+poll+staple run, clean up work/ and artifacts/ and restart the periodic puppet launch daemon, f) unquarantine, and then g) push master to production-mac-signing to roll out everywhere.

(Yolo is push to production-mac-signing with some non-zero chance of needing Relops to help us rescue the pool.)

2021-09-03 15:48 UTC, escapewindow commented on modules/signing_worker/files/requirements.dep.txt
> +jwcrypto==1.0 \
Nothing's jumping out at me: https://github.com/latchset/jwcrypto/releases/tag/v1.0.0

2021-09-07 17:19 UTC, bhearsum commented
In testing this I discovered that `notarization_poller` calls `claimWork` itself and needed a patch: https://github.com/mozilla-releng/scriptworker-scripts/pull/395

This PR will need an update after that one is merged.

2021-09-07 18:16 UTC, bhearsum commented
Planning to roll this out tomorrow.

2021-09-09 14:26 UTC, escapewindow approved these changes

2021-09-09 14:27 UTC, escapewindow commented on modules/signing_worker/files/requirements.dep.txt
> +jwcrypto==1.0 \
Oops, I thought I stamped it at this point. Sorry!

2021-09-10 13:24 UTC, merged